Fixes get_members decoding
zabirauf/ex_microsoftbot pull request #18
Opened 2019-04-25 15:43 UTC by jmnsf

Getting members of a conversation returns an array of channel members which is
currently being parsed as a map, thereby failing. Also fixes the return of the
`parse` function, as it doesn't match the spec.

2019-04-26 10:00 UTC, zabirauf commented
Thanks @jmnsf for the PR. I'll take a look at it.

2019-04-26 10:04 UTC, zabirauf requested changes

2019-04-26 10:04 UTC, zabirauf commented on lib/models/channel_account.ex
> +  @doc false
Use `defp` or inline it in the `parse` function `Poison.Decode.decode(param, as: [decoding_map()])`

2019-04-26 11:17 UTC, jmnsf commented
@zabirauf np, thanks for the lib 👍

2019-04-26 12:32 UTC, zabirauf commented on lib/models/channel_account.ex
> +    parse Poison.decode!(param)
This changes the type as currently it would return ChannelAccount when parsed but with this change it will return {:ok, ChannelAccount}

2019-04-27 06:32 UTC, zabirauf requested changes

2019-04-27 06:32 UTC, zabirauf commented on lib/models/channel_account.ex
> +    Poison.Decode.decode(param, as: [decoding_map()])
Wouldn't this also change the type to be ChannelAccount instead of {:ok, ChannelAccount}?

2019-04-27 06:32 UTC, zabirauf commented on lib/models/channel_account.ex
> +    Poison.Decode.decode(param, as: decoding_map())
Same

2019-04-27 06:32 UTC, zabirauf commented on lib/models/channel_account.ex
> +    Poison.Decode.decode(param, as: decoding_map())
This still returns the incorrect type. As `Posion.Decode.decode` returns only value and not `{:ok, value}`

2019-04-27 06:32 UTC, zabirauf commented on lib/models/channel_account.ex
> +    Poison.Decode.decode(param, as: [decoding_map()])
This still returns the incorrect type. As Posion.Decode.decode returns only value and not {:ok, value}

2019-04-27 09:23 UTC, jmnsf commented
@zabirauf you're probably right, I was using the wrong Poison lib docs as reference. Let me give this another spin, I might add some tests to make sure data's being returned as expected.

2019-04-27 09:42 UTC, jmnsf commented
@zabirauf there we go, sorry about the back and forth.

If I could make a suggestion, it's a bit unexpected that the `parse/1` function doesn't always return the same type, could be worth a new major to make the interface consistent? Disregard if this is normal in elixir, still learning the language.

2019-04-28 10:20 UTC, zabirauf commented
@jmnsf I agree that there is definitely room for improvement to make it more consistent. I don't recall the historical context for why I did it this way :). 
I'll create an issue to make it consistent in case someone wants to pick it up.
Thanks a lot for adding tests!

2019-04-28 10:21 UTC, merged